name: flutter_bigpay_movie_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  bloc_test: ^9.1.7
  cached_network_image: ^3.4.1
  dev: ^1.0.0
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.2
  http: ^1.2.2
  injectable: ^2.5.0
  injectable_generator: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - .env

